# Generated by Django 4.2.5 on 2023-09-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(null=True, upload_to='birth_certificate'),
        ),
        migrations.AddField(
            model_name='student',
            name='certificate_of_origin',
            field=models.FileField(null=True, upload_to='certificate_of_origin'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pendng'), ('disapprove', 'Disapprove')], default='pending', max_length=50),
        ),
    ]
