# Generated by Django 4.2.5 on 2023-09-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_student_birth_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='department_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
